services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NormanSeibert\Ldap\:
    resource: '../Classes/*'

  NormanSeibert\Ldap\Command\ImportUsersCommand:
    tags:
      - name: 'console.command'
        command: 'ldap:importUsers'

  NormanSeibert\Ldap\Command\UpdateUsersCommand:
    tags:
      - name: 'console.command'
        command: 'ldap:updateUsers'

  NormanSeibert\Ldap\Command\ImportOrUpdateUsersCommand:
    tags:
      - name: 'console.command'
        command: 'ldap:importOrUpdateUsers'

  NormanSeibert\Ldap\Command\DeleteUsersCommand:
    tags:
      - name: 'console.command'
        command: 'ldap:deleteUsers'

  NormanSeibert\Ldap\Service\LdapAuthService:
    public: true

  NormanSeibert\Ldap\Service\LdapImporter:
    public: true

  NormanSeibert\Ldap\Domain\Model\Configuration\LdapConfiguration:
    public: true

  NormanSeibert\Ldap\Domain\Model\LdapServer\LdapServer:
    public: true

  NormanSeibert\Ldap\Domain\Model\LdapUser\FeUser:
    public: true

  NormanSeibert\Ldap\Domain\Model\LdapUser\FeGroup:
    public: true

  NormanSeibert\Ldap\Domain\Model\LdapUser\BeUser:
    public: true

  NormanSeibert\Ldap\Domain\Model\LdapUser\BeGroup:
    public: true